-- Script SQL para cargar artículos y stock inicial (entradas)
-- Generado automáticamente

-- 1. Insertar artículos
INSERT INTO articles (code, name, unit, description, min_stock, max_stock, status)
VALUES
('A001', 'Abrazadera omega', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A002', 'Abrazadera omega', 'pieza', '1" pulgada', 0, 0, 'activo'),
('A003', 'Abrazadera unicanal', 'pieza', '3/4 pulgada', 0, 0, 'activo'),
('A004', 'Abrazadera unicanal', 'pieza', '1" pulgada', 0, 0, 'activo'),
('E005', 'ABRAZADERA UNIVERSAL', 'Bolsas', '2 pzas por bolsa', 0, 0, 'activo'),
('A005', 'Abrazaderas para tierra (Va en la varilla)', 'pieza', 'va en la varilla', 0, 0, 'activo'),
('A006', 'Anclaje quimico', 'pieza', '0', 0, 0, 'activo'),
('E024', 'Angulo Riel', 'm', '2m', 0, 0, 'activo'),
('E023', 'Angulo Riel', 'm', '4m', 0, 0, 'activo'),
('A007', 'cable desnudo', 'metro', '12AWG', 0, 0, 'activo'),
('A008', 'cable desnudo', 'metro', '10AWG', 0, 0, 'activo'),
('C009', 'Cable negro', 'metro', '12 AWG', 0, 0, 'activo'),
('C008', 'Cable negro', 'metro', '8 AWG', 0, 0, 'activo'),
('C007', 'Cable negro', 'metro', '10 AWG', 0, 0, 'activo'),
('C006', 'Cable negro', 'metro', '6 AWG', 0, 0, 'activo'),
('C005', 'Cable negro', 'metro', '1x10', 0, 0, 'activo'),
('C011', 'Cable rojo', 'metro', '1x10', 0, 0, 'activo'),
('A009', 'Cable THW', 'metro', '10 AWG', 0, 0, 'activo'),
('A010', 'cable uso rudo', 'metro', '3x10', 0, 0, 'activo'),
('C010', 'Cable verde', 'metro', '12 AWG', 0, 0, 'activo'),
('A011', 'Caja sencilla strim', 'caja', '25 amp', 0, 0, 'activo'),
('A012', 'centro de carga qo2', 'pieza', '', 0, 0, 'activo'),
('A013', 'Centros de carga', 'pieza', '2 espacios 127-220 Volts', 0, 0, 'activo'),
('E002', 'CINCHOS', 'pieza', '2.5x101.6mm', 0, 0, 'activo'),
('E001', 'CINCHOS', 'pieza', '4.6 x288mm', 0, 0, 'activo'),
('E003', 'CINCHOS NEGROS', 'pieza', '3x150mm', 0, 0, 'activo'),
('A014', 'Cinta de aislar', 'pieza', '0', 0, 0, 'activo'),
('A015', 'Cinta Vulcanizada Scotch', 'pieza', '0', 0, 0, 'activo'),
('A016', 'Clavija', 'pieza', '15 Amp', 0, 0, 'activo'),
('E006', 'CLIPS DE CONEXIÓN PARA NEXT RAIL', 'pieza', '4 piezas por bolsa', 0, 0, 'activo'),
('A017', 'Conduit LB', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A018', 'Conduit LB', 'pieza', '1" pulgada', 0, 0, 'activo'),
('A019', 'Conduit LR', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A020', 'Conduit LR', 'pieza', '1" pulgada', 0, 0, 'activo'),
('A021', 'Conduit LL', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A022', 'Condulet  LL', 'pieza', '1"', 0, 0, 'activo'),
('A023', 'Condulet  T', 'pieza', '1"', 0, 0, 'activo'),
('A024', 'Condulet  T', 'pieza', '3/4"', 0, 0, 'activo'),
('E032', 'Conector angulo riel', 'pieza', '', 0, 0, 'activo'),
('A025', 'Conector hermetico', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A026', 'Conector hermetico', 'pieza', '1" pulgada', 0, 0, 'activo'),
('A027', 'Conector hermetico', 'pieza', '1/2" pulgada', 0, 0, 'activo'),
('A028', 'Conector recto', 'pieza', '3/4 " pulgada', 0, 0, 'activo'),
('A029', 'Conector recto', 'pieza', '1 " pulgada', 0, 0, 'activo'),
('A030', 'Conector recto', 'pieza', '1/2 " pulgada', 0, 0, 'activo'),
('A031', 'Cople de P.D', 'pieza', '3/4"', 0, 0, 'activo'),
('A032', 'Cople de P.D', 'pieza', '1"', 0, 0, 'activo'),
('A033', 'Cople de P.G', 'pieza', '1"', 0, 0, 'activo'),
('A034', 'Cople de P.G', 'pieza', '3/4"', 0, 0, 'activo'),
('A035', 'Curva P.D', 'pieza', '3/4"', 0, 0, 'activo'),
('A036', 'Curva P.D', 'pieza', '1"', 0, 0, 'activo'),
('A037', 'Curva P.G.', 'pieza', '1"', 0, 0, 'activo'),
('A038', 'Curva P.G.', 'pieza', '1 1/2"', 0, 0, 'activo'),
('A039', 'Curva P.G.', 'pieza', '3/4"', 0, 0, 'activo'),
('A040', 'Disco de corte', 'pieza', '4 1/2"', 0, 0, 'activo'),
('A041', 'Duretan', 'Tubo', '300 ml', 0, 0, 'activo'),
('A042', 'Empalmes de riel con puesta tierra', 'pieza', '0', 0, 0, 'activo'),
('E025', 'Esparrago', 'pieza', '1.50 mts', 0, 0, 'activo'),
('A043', 'Ferrules', 'pieza', '22', 0, 0, 'activo'),
('A044', 'Ferrules', 'pieza', '20', 0, 0, 'activo'),
('A045', 'Ferrules', 'pieza', '18', 0, 0, 'activo'),
('A046', 'Ferrules', 'pieza', '16', 0, 0, 'activo'),
('A047', 'Ferrules', 'pieza', '14', 0, 0, 'activo'),
('A048', 'Ferrules', 'pieza', '12', 0, 0, 'activo'),
('A049', 'Ferrules', 'pieza', '10', 0, 0, 'activo'),
('A050', 'Ferrules', 'pieza', '8', 0, 0, 'activo'),
('A051', 'Fusibles', 'pieza', '20 A', 0, 0, 'activo'),
('A052', 'Fusibles', 'pieza', '25 A', 0, 0, 'activo'),
('A053', 'Fusibles', 'pieza', '32 A', 0, 0, 'activo'),
('A054', 'Glandulas', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A055', 'Glandulas', 'pieza', '1" pulgada', 0, 0, 'activo'),
('A056', 'impermeabilizante', 'litros', 'blanco', 0, 0, 'activo'),
('V002', 'Inversor', 'pieza', '3600 W', 0, 0, 'activo'),
('V001', 'Inversor', 'pieza', '6000 W', 0, 0, 'activo'),
('A057', 'ITM', 'pieza', '2X65 A', 0, 0, 'activo'),
('A058', 'ITM DC', 'pieza', '1000 V 10 A', 0, 0, 'activo'),
('E016', 'Llave para MC4', 'pieza', '', 0, 0, 'activo'),
('E014', 'MC4 Hembra', 'pieza', '61x18,8 mm', 0, 0, 'activo'),
('E017', 'MC4 Macho', 'pieza', '61x18,8 mm', 0, 0, 'activo'),
('A059', 'monitor', 'pieza', '0.75', 0, 0, 'activo'),
('A060', 'Ojillos', 'pieza', '12 AWG', 0, 0, 'activo'),
('A061', 'Ojillos', 'pieza', '8 AWG', 0, 0, 'activo'),
('A062', 'OT    3/4"', 'pieza', '3/4"', 0, 0, 'activo'),
('A063', 'OT 1"', 'pieza', '1"', 0, 0, 'activo'),
('E029', 'Panel LONGI', 'pieza', '555 W', 0, 0, 'activo'),
('E031', 'Panel MAXEON', 'pieza', '0', 0, 0, 'activo'),
('E030', 'Panel PERFORMANCE', 'pieza', '0', 0, 0, 'activo'),
('A064', 'Perfil', 'metro', '4.2', 0, 0, 'activo'),
('A065', 'Perfil', 'metro', '4.8', 0, 0, 'activo'),
('A066', 'Pija', 'pieza', '1/4"x1"', 0, 0, 'activo'),
('A067', 'Pija', 'pieza', '1/4"x2"', 0, 0, 'activo'),
('A068', 'Pija', 'pieza', '3/8x 2 1/2"', 0, 0, 'activo'),
('A069', 'Pija cabeza hexagonal', 'pieza', '3/8"x 1"', 0, 0, 'activo'),
('A070', 'Pijabroca', 'pieza', '1/4 - 2 "', 0, 0, 'activo'),
('E009', 'PIJABROCAS', 'pieza', '2"', 0, 0, 'activo'),
('A071', 'Pijabrocas', 'pieza', '1/2"', 0, 0, 'activo'),
('A072', 'Pijas', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A073', 'Pijas', 'pieza', '2 Y 3/4 "', 0, 0, 'activo'),
('A074', 'Pijas', 'pieza', '5/8" pulgada', 0, 0, 'activo'),
('A075', 'Pijas', 'pieza', '#8x1 1/2"', 0, 0, 'activo'),
('A076', 'Pijas', 'pieza', 'Para taquete 7/16"', 0, 0, 'activo'),
('A077', 'Pija', 'pieza', '1 1/2"', 0, 0, 'activo'),
('A078', 'Pija', 'pieza', '1/2"', 0, 0, 'activo'),
('A079', 'Pijas', 'pieza', '#12x2"', 0, 0, 'activo'),
('V006', 'Pijas para madera', 'pieza', '3.5mm x 41.3mm', 0, 0, 'activo'),
('V005', 'Pijas para madera', 'pieza', '3.5mm x 25.4mm', 0, 0, 'activo'),
('A080', 'Portafusibles', 'pieza', '30 A', 0, 0, 'activo'),
('A081', 'Portafusibles', 'pieza', '32 A', 0, 0, 'activo'),
('A082', 'Portafusibles', 'pieza', '25 A', 0, 0, 'activo'),
('A083', 'Quinta Terminal', 'pieza', 'Medidor 110 - 220', 0, 0, 'activo'),
('E013', 'Rondanas', 'pieza', '3/8"', 0, 0, 'activo'),
('A084', 'Sincronizadores para inversores', 'pieza', '', 0, 0, 'activo'),
('E019', 'Soporte ajustable delantero', 'pieza', '', 0, 0, 'activo'),
('E020', 'Soporte ajustable trasero', 'pieza', '', 0, 0, 'activo'),
('E004', 'SOPORTE L', 'pieza', '105mm', 0, 0, 'activo'),
('V004', 'String', 'pieza', '1', 0, 0, 'activo'),
('V003', 'String', 'pieza', '2', 0, 0, 'activo'),
('A085', 'Supresor de picos DC', 'pieza', '600 V', 0, 0, 'activo'),
('A086', 'Taquete', 'pieza', '1/4"', 0, 0, 'activo'),
('A087', 'Taquete Azúl', 'pieza', '3/8" pulgada', 0, 0, 'activo'),
('A088', 'Taquete blanco', 'bolsa', '0', 0, 0, 'activo'),
('A089', 'taquete expansivo', 'pieza', '3/4"', 0, 0, 'activo'),
('A090', 'Taquete expansivo', 'pieza', '1/2"', 0, 0, 'activo'),
('A091', 'Taquete expansivo', 'pieza', '3/8"', 0, 0, 'activo'),
('A092', 'Taquete expansivo tipo Z', 'pieza', '5 1/6 x2', 0, 0, 'activo'),
('A093', 'Taquete gris', 'bolsa', '0', 0, 0, 'activo'),
('A094', 'Taquete Tipo Z', 'pieza', '5/8"', 0, 0, 'activo'),
('A095', 'Taquete Tipo Z', 'pieza', '1/4"', 0, 0, 'activo'),
('A096', 'Taquetes', 'pieza', '1/4"', 0, 0, 'activo'),
('A097', 'Taquetes Azules', 'pieza', '3/8"', 0, 0, 'activo'),
('A098', 'Taquetes blancos', 'pieza', '3/4"', 0, 0, 'activo'),
('A099', 'Taquetes blancos', 'pieza', '1/2"', 0, 0, 'activo'),
('E012', 'TAQUETES EXPANSIVOS', 'pieza', 'M12X100', 0, 0, 'activo'),
('E007', 'TAQUETES EXPANSIVOS', 'pieza', '3/8"', 0, 0, 'activo'),
('E011', 'TAQUETES EXPANSIVOS DORADOS', 'pieza', '5/8"', 0, 0, 'activo'),
('A100', 'Taquetes grises', 'pieza', '3/8"', 0, 0, 'activo'),
('E022', 'Tbolts', 'pieza', '', 0, 0, 'activo'),
('A101', 'Terminal de Conexión Tierra', 'pieza', '0', 0, 0, 'activo'),
('E015', 'Terminal de MC4 Hembra', 'pieza', '61x18,8 mm', 0, 0, 'activo'),
('E018', 'Terminal de MC4 Macho', 'pieza', '61x18,8 mm', 0, 0, 'activo'),
('A102', 'Tornillo  3/8', 'pieza', '0', 0, 0, 'activo'),
('A103', 'Tornillos', 'pieza', '2"', 0, 0, 'activo'),
('L003', 'Tubo Licuatite', 'pieza', '1"', 0, 0, 'activo'),
('L002', 'Tubo Licuatite', 'pieza', '3/4"', 0, 0, 'activo'),
('L001', 'Tubo Licuatite', 'pieza', '1/2"', 0, 0, 'activo'),
('T011', 'Tubo P.D', 'pieza', '3/4"', 0, 0, 'activo'),
('T009', 'Tubo P.D', 'pieza', '1 1/2"', 0, 0, 'activo'),
('T008', 'Tubo P.D', 'pieza', '1/2"', 0, 0, 'activo'),
('T005', 'Tubo P.D', 'pieza', '1"', 0, 0, 'activo'),
('T004', 'Tubo P.G C/COPLE', 'pieza', '1"', 0, 0, 'activo'),
('T001', 'Tubo P.G C/COPLE', 'pieza', '3/4"', 0, 0, 'activo'),
('E021', 'Tuercas', 'pieza', '5/16"', 0, 0, 'activo'),
('A104', 'Tuercas general', 'pieza', '3/8', 0, 0, 'activo'),
('A105', 'Unicanal', 'pieza', '3.57 mts', 0, 0, 'activo'),
('E028', 'Unical', 'pieza', '1.10 mts', 0, 0, 'activo'),
('E027', 'Unical', 'pieza', '2.30 mts', 0, 0, 'activo'),
('E026', 'Unical', 'pieza', '2 mts', 0, 0, 'activo'),
('A106', 'Unicanal', 'pieza', '2 mts', 0, 0, 'activo'),
('A107', 'Unicanal', 'pieza', '2.30 mts', 0, 0, 'activo'),
('A108', 'Unicanal', 'pieza', '1.10 mts', 0, 0, 'activo'),
('A109', 'Unicanal', 'pieza', '4x4 m', 0, 0, 'activo'),
('A110', 'Uñas para tubo conduit', 'pieza', '3/4" pulgada', 0, 0, 'activo'),
('A111', 'Uñas para tubo conduit', 'pieza', '1" pulgada', 0, 0, 'activo'),
('A112', 'Curva P.G.', 'pieza', '1 1/2"', 0, 0, 'activo'),
('A113', 'Cinchos negros', 'pieza', '300x4.5mm', 0, 0, 'activo'),
('A114', 'Cinchos negros', 'pieza', '4.8x370mm', 0, 0, 'activo'),
('A115', 'Cinchos negros', 'pieza', '190x4.8mm', 0, 0, 'activo'),
('A116', 'Glandulas', 'pieza', '1/4"', 0, 0, 'activo'),
('A117', 'impermeabilizante', 'litros', 'rojo', 0, 0, 'activo'),
('A118', 'Pija', 'pieza', '2 1/2"', 0, 0, 'activo'),
('A119', 'Ojillo', 'pieza', 'D12AW', 0, 0, 'activo'),
('A120', 'Abrazadera uña', 'pieza', '3/4"', 0, 0, 'activo'),
('A121', 'Uña para tubo conduit', 'pieza', '1/2"', 0, 0, 'activo');

-- 2. Insertar entradas de inventario (stock inicial)
-- NOTA: Requiere que los artículos ya existan y que se conozca el article_id
-- Se asume unit_cost = 0, proveedor = 'Carga inicial', fecha = CURRENT_TIMESTAMP
-- Ejemplo para un artículo:
-- (SELECT article_id FROM articles WHERE code = 'A001'), cantidad, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP
INSERT INTO inventory_entries (article_id, quantity, unit_cost, invoice_number, supplier, date)
VALUES
( (SELECT article_id FROM articles WHERE code = 'A001'), 22, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A003'), 8, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E005'), 1, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A005'), 15, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A007'), 40, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A008'), 47.2, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C009'), 139, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C008'), 1.5, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C007'), 64.75, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C006'), 1.5, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C005'), 273, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C011'), 767, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'C010'), 35, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E002'), 32, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E006'), 100, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A017'), 17, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A018'), 4, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A019'), 8, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A021'), 8, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A025'), 4, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A026'), 2, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A027'), 31, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A028'), 84, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A029'), 25, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A030'), 89, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A031'), 151, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A032'), 26, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A037'), 3, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A038'), 3, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A039'), 18, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A040'), 4, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A041'), 1, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A043'), 357, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A044'), 369, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A045'), 376, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A046'), 400, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A047'), 500, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A048'), 121, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A049'), 877, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A050'), 127, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A054'), 7, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A055'), 3, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A056'), 15, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E016'), 10, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E014'), 70, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E017'), 88, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A061'), 19, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A062'), 28, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A063'), 4, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A064'), 0, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A065'), 0, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A067'), 26, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A072'), 84, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A073'), 10, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A077'), 30, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A078'), 8, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E013'), 199, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E019'), 1, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E004'), 1, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A087'), 189, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A098'), 29, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E012'), 12, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'E022'), 131, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'L002'), 6.5, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'L001'), 5, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'T011'), 3, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'T004'), 16, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'T001'), 171, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A113'), 18, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A114'), 176, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A115'), 52, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A117'), 15, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A118'), 30, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A119'), 7, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A120'), 86, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP),
( (SELECT article_id FROM articles WHERE code = 'A121'), 10, 0, NULL, 'Carga inicial', CURRENT_TIMESTAMP);

-- 3. (Opcional) Insertar salidas de inventario si hay stock negativo o ajustes
-- Ningún artículo tiene stock negativo en la hoja proporcionada.
